name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - run: composer install --working-dir=vendor/swoole/ide-helper

      - uses: docker://phpswoole/swoole:4.5.2-php7.1
        with:
          args: vendor/swoole/ide-helper/bin/generator.php

      - run: mv vendor/swoole/ide-helper/output swoole-meta
      - run: ls -la swoole-meta
