name: 'PHP Composer'
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: 'Validate composer.json and composer.lock'
        run: 'composer validate --ansi'
      - name: 'Get Composer Cache Directory'
        id: composer-cache
        run: 'echo "::set-output name=dir::$(composer config cache-dir)"'
      - uses: actions/cache@v2.1.7
        with:
          path: '${{ steps.composer-cache.outputs.dir }}'
          key: '${{ runner.os }}-composer-${{ hashFiles(''**/composer.lock'') }}'
          restore-keys: '${{ runner.os }}-composer-'
      - name: 'Install dependencies'
        run: 'composer install --prefer-dist --no-progress --no-suggest'
      - run: 'mv vendor/swoole/ide-helper/src swoole-meta'
      - run: 'zip -r phpstorm-swoole-plugin.jar META-INF swoole-meta'
      - name: Create a release and attach files
        run: |
          tagname="${GITHUB_REF#refs/tags/}"
          gh release create "$tagname" phpstorm-swoole-plugin.jar
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: 'Upload to marketplace'
        env:
          JETBRAINS_TOKEN: '${{ secrets.JETBRAINS_TOKEN }}'
        run: 'curl -i --header "Authorization: Bearer $JETBRAINS_TOKEN" -F xmlId=me.elabee.idea.plugin.swoole -F file=@phpstorm-swoole-plugin.jar -F channel=stable https://plugins.jetbrains.com/plugin/uploadPlugin'
